drop distribute from requirements.txt
when i first ran pip install -r requirements.txt, i got the stack trace below. a few internet searches led me to believe distribute==0.6.28 was the culprit. removing it fixed pip install, and the actual code seems to run fine without it.

Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/private/var/folders/y_/7mgz0yqd3hlgg2drhqx4ggf80000gn/T/pip-build-xbgIJ0/distribute/setup.py", line 220, in <module>
    scripts = scripts,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "pkg_resources.py", line 2029, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "pkg_resources.py", line 825, in best_match
    return self.obtain(req, installer) # try and download/install
  File "pkg_resources.py", line 837, in obtain
    return installer(requirement)
  File "setuptools/dist.py", line 272, in fetch_build_egg
    dist = self.__class__({'script_args':['easy_install']})
  File "setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
...
  File "setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "pkg_resources.py", line 2029, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "pkg_resources.py", line 579, in resolve
    env = Environment(self.entries)
  File "pkg_resources.py", line 748, in __init__
    self.scan(search_path)
  File "pkg_resources.py", line 777, in scan
    for dist in find_distributions(item):
  File "pkg_resources.py", line 1757, in find_on_path
    path_item,entry,metadata,precedence=DEVELOP_DIST
  File "pkg_resources.py", line 2151, in from_location
    py_version=py_version, platform=platform, **kw
  File "pkg_resources.py", line 2128, in __init__
    self.project_name = safe_name(project_name or 'Unknown')
  File "pkg_resources.py", line 1139, in safe_name
    return re.sub('[^A-Za-z0-9.]+', '-', name)
RuntimeError: maximum recursion depth exceeded